//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE.Models
{
    public partial class CompletedTask
    {
        public int TaskID { get; set; }
        public string TaskName { get; set; }
        public string AssignedUser { get; set; }
        public System.DateTime DateTimeCompleted { get; set; }
        public double TotalTime { get; set; }
        public int id { get; set; }
    }
}
