//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailedStep
    {
        public int DetailedStepID { get; set; }
        public int MainStepID { get; set; }
        public string DetailedStepName { get; set; }
        public string DetailedStepText { get; set; }
        public string ImageFilename { get; set; }
        public string ImagePath { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int ListOrder { get; set; }
    
        public virtual MainStep MainStep { get; set; }
    }
}
