//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainStep
    {
        public MainStep()
        {
            this.CompletedMainSteps = new HashSet<CompletedMainStep>();
            this.DetailedSteps = new HashSet<DetailedStep>();
        }
    
        public int MainStepID { get; set; }
        public int TaskID { get; set; }
        public string MainStepName { get; set; }
        public string MainStepText { get; set; }
        public Nullable<double> MainStepTime { get; set; }
        public string AudioFilename { get; set; }
        public string AudioPath { get; set; }
        public string VideoFilename { get; set; }
        public string VideoPath { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int ListOrder { get; set; }
    
        public virtual ICollection<CompletedMainStep> CompletedMainSteps { get; set; }
        public virtual ICollection<DetailedStep> DetailedSteps { get; set; }
        public virtual Task Task { get; set; }
    }
}
