//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberAssignment
    {
        public MemberAssignment()
        {
            this.CategoryAssignments = new HashSet<CategoryAssignment>();
            this.CompletedMainSteps = new HashSet<CompletedMainStep>();
            this.TaskAssignments = new HashSet<TaskAssignment>();
            this.Tasks = new HashSet<Task>();
        }
    
        public string AssignedUser { get; set; }
        public string AssignedSupervisor { get; set; }
    
        public virtual ICollection<CategoryAssignment> CategoryAssignments { get; set; }
        public virtual ICollection<CompletedMainStep> CompletedMainSteps { get; set; }
        public virtual ICollection<TaskAssignment> TaskAssignments { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
