//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestedCategory
    {
        public int CategoryID { get; set; }
        public bool IsApproved { get; set; }
        public string RequestingUser { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
