//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskAssignment
    {
        public int CategoryID { get; set; }
        public int TaskID { get; set; }
        public string AssignedUser { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual MemberAssignment MemberAssignment { get; set; }
        public virtual Task Task { get; set; }
    }
}
