//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.CompletedMainSteps = new HashSet<CompletedMainStep>();
            this.MainSteps = new HashSet<MainStep>();
        }
    
        public int TaskID { get; set; }
        public int CategoryID { get; set; }
        public string TaskName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<CompletedMainStep> CompletedMainSteps { get; set; }
        public virtual ICollection<MainStep> MainSteps { get; set; }
    }
}
