//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTaskRequest
    {
        public int ID { get; set; }
        public string TaskName { get; set; }
        public string TaskDescription { get; set; }
        public System.DateTime DateComplete { get; set; }
        public string UserName { get; set; }
    
        public virtual UserTaskRequest UserTaskRequests1 { get; set; }
        public virtual UserTaskRequest UserTaskRequest1 { get; set; }
    }
}
